version: "3"
services:

  haproxy:
    image: haproxy:lts-alpine
    container_name: dwc_haproxy
    restart: unless-stopped
    networks:
      dwc-mcvlan:
        ipv4_address: 192.168.178.20
    ports:
      - 80:80
    volumes:
     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    sysctls:
     - net.ipv4.ip_unprivileged_port_start=0

  dwc:
    build: .
    container_name: dwc_server
    restart: unless-stopped
    networks:
      dwc-mcvlan:
        ipv4_address: 192.168.178.21
    ports:
      - 8000:8000
      - 9000:9000
      - 9001:9001
      - 9003:9003
      - 9009:9009
      - 9998:9998
      - 27500:27500
      - 28910:28910
      - 29900:29900
      - 29901:29901
      - 29920:29920
      - 27900:27900/udp
      - 27901:27901/udp
    volumes:
      - data:/dwc/data

networks:
  dwc-mcvlan:
    ipam:
      driver: default
      config:
        - subnet: 192.168.178.0/24


volumes:
  data:
